import React from 'react';
import GradeInterpretation from './GradeInterpretation';
import './TerminalReport.css';
import TeacherRemark from './TeacherRemark';


const TerminalReport = (props) => {

  return (
    <div className="TerminalReport">
      <TeacherRemark></TeacherRemark>
      <GradeInterpretation></GradeInterpretation>
      <p>Generated by Jephthah & Blay Gradebook App (c) 2024</p>
    </div>
  );
};

export default TerminalReport;


// {data.map((item) => (
//   <tr key={item.id}>
//     <td style={{ border: '1px solid white', padding: '8px' }}>{item.id}</td>
//   </tr>
// ))}

